import uuid

from django.conf import settings
from django.db import models


class FeedItem(models.Model):
    """
    Pre-computed feed item for a user's timeline.
    Items are generated by the FeedAlgorithm and cached for fast retrieval.
    """

    ITEM_TYPE_CHOICES = [
        ("post", "Post"),
        ("share", "Share"),
        ("group_post", "Group Post"),
        ("suggestion", "Suggestion"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="feed_items",
        db_index=True,
    )
    content_type = models.CharField(max_length=15, choices=ITEM_TYPE_CHOICES)
    post = models.ForeignKey(
        "posts.Post",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="feed_entries",
    )
    share = models.ForeignKey(
        "posts.Share",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="feed_entries",
    )
    score = models.FloatField(default=0.0, db_index=True)
    is_seen = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "feed_items"
        ordering = ["-score", "-created_at"]
        indexes = [
            models.Index(fields=["user", "-score", "-created_at"]),
        ]

    def __str__(self):
        return f"Feed item for {self.user.username} ({self.content_type})"


class FeedAlgorithm(models.Model):
    """
    Stores tunable parameters for the feed ranking algorithm.
    """

    name = models.CharField(max_length=100, unique=True)
    recency_weight = models.FloatField(
        default=0.3,
        help_text="Weight given to how recently the post was created",
    )
    engagement_weight = models.FloatField(
        default=0.4,
        help_text="Weight given to likes, comments, and shares",
    )
    relationship_weight = models.FloatField(
        default=0.2,
        help_text="Weight based on friendship closeness and interaction history",
    )
    diversity_weight = models.FloatField(
        default=0.1,
        help_text="Weight to ensure content variety in the feed",
    )
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "feed_algorithms"

    def __str__(self):
        return f"{self.name} ({'active' if self.is_active else 'inactive'})"

    def total_weight(self):
        return (
            self.recency_weight
            + self.engagement_weight
            + self.relationship_weight
            + self.diversity_weight
        )
